MoviesReviews.UI/Controllers/GenreController.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using MoviesReviews.Core.Domain.Entities;
using ServiceContracts;

namespace Movie_Review_Website.Controllers;

public class GenreController : Controller
{
    private readonly ILogger<GenreController> _logger;
    private readonly IGenreService _genreService;
    public GenreController(ILogger<GenreController> logger, IGenreService genreService)
    {
        _genreService = genreService;
        _logger = logger;
    }
    public async Task<IActionResult> Index()
    {
        _logger.LogInformation("Getting all genres");
       IEnumerable<Genre> genres = await _genreService.GetAllGenresAsync();
        return View(genres);
    }

    [HttpGet]
    public IActionResult Add()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Add(Genre genre)
    {
        if (genre.Name.IsNullOrEmpty() || !ModelState.IsValid)
        {
            _logger.LogInformation($"{genre.Name} Not Valid");
            return View("Error");
        }
        _logger.LogInformation($"{genre.Name} is Valid");
        await _genreService.AddGenreAsync(genre);
        return RedirectToAction("index");
    }
}

MoviesReviews.UI/Controllers/MoviesController.cs
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Movie_Review_Website.Filters;
using MoviesReviews.Core.Domain.Entities;
using Rotativa.AspNetCore;
using ServiceContracts;

namespace Movie_Review_Website.Controllers;

[Authorize]
[Route("[controller]/[action]")]
public class MoviesController : Controller
{
    private readonly ILogger<MoviesController> _logger;
    private readonly IMovieService _movieService;
    private readonly IGenreService _genreService;
    public MoviesController(ILogger<MoviesController> logger, IMovieService movieService, IGenreService genreService)
    {
        _logger = logger;
        _movieService = movieService;
        _genreService = genreService;
    }

    [HttpGet]
    [Route("/")]
    [ValidateSearch]
    public async Task<IActionResult> Index(string? searchString, string? genreString)
    {
        _logger.LogInformation("MoviesController - Index method invoked");

        if (!string.IsNullOrEmpty(searchString))
        {
            _logger.LogDebug($"Search string provided: {searchString}");

            // Only load movies if search string is present
            IEnumerable<Movie> movies = await _movieService.GetAllMoviesAsync();
            Movie? movie = movies.FirstOrDefault(tmp => tmp.Title.Contains(searchString, StringComparison.OrdinalIgnoreCase));

            if (movie == null)
            {
                _logger.LogWarning("No movie found for the search string.");
                return View("NotFound");
            }
            ViewBag.searchString = searchString;
            return View("SearchResult", movie);
        }
        else if (!string.IsNullOrEmpty(genreString))
        {
            _logger.LogInformation($"Searching using Genre {genreString}");
            IEnumerable<Movie> movies = await _movieService.GetAllMoviesAsync();
            movies = movies.Where(tmp => tmp.Genre.Name.Contains(genreString, StringComparison.OrdinalIgnoreCase));
            ViewBag.genreString = genreString;
            return View(movies);
        }

        // If no search string, return all movies
        IEnumerable<Movie> allMovies = await _movieService.GetAllMoviesAsync();
        _logger.LogDebug("All movies loaded.");
        return View(allMovies);
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        _logger.LogInformation($"MoviesController - Edit method invoked with id: {id}");
        Movie? movie = await _movieService.GetMovieByIdAsync(id);
        if (movie == null)
        {
            _logger.LogWarning($"Movie not found: {id}");
            return View("Error");
        }
        _logger.LogInformation($"Movie found: {movie.Title}");
        ViewBag.genres = await _genreService.GetAllGenresAsync();
        ViewBag.errors = new List<string>(); // Initialize ViewBag.errors
        return View(movie);
    }
    [HttpPost]
    public async Task<IActionResult> Edit(Movie movie, IFormFile? ImageFile)
    {
        if (ModelState.IsValid)
        {
            if (ImageFile != null && ImageFile.Length > 0)
            {
                // Upload the new image and update the image path
                var filePath = Path.Combine("wwwroot/images", ImageFile.FileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(stream);
                }
                movie.ImagePath = "/images/" + ImageFile.FileName;
            }
            else
            {
                // Retrieve the existing movie to keep its current image path
                var existingMovie = await _movieService.GetMovieByIdAsync(movie.MovieId);
                if (existingMovie != null)
                {
                    movie.ImagePath = existingMovie.ImagePath; // Keep the old image path
                }
            }

            try
            {
                await _movieService.UpdateMovieAsync(movie);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MovieExists(movie.MovieId))
                {
                    return View("NotFound");
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        return View(movie);
    }

    private bool MovieExists(int id)
    {
        return _movieService.GetAllMoviesAsync().Result.Any(e => e.MovieId == id);
    }


    public async Task<IActionResult> Delete(int id)
    {
        _logger.LogWarning($"MoviesController - Delete method invoked with id: {id}");
        Movie? movie = await _movieService.GetMovieByIdAsync(id);
        if (movie == null)
        {
            _logger.LogError($"Movie Not found");
            return View("Error");
        }
        else
        {
            _logger.LogInformation($"Movie Deleted");
            await _movieService.DeleteMovieAsync(id);
            return RedirectToAction("Index");
        }
    }

    [HttpGet]
    public async Task<IActionResult> Add()
    {
        _logger.LogInformation("Rendering The View");
        ViewBag.genres = await _genreService.GetAllGenresAsync();
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Add(Movie movie, IFormFile? ImagePath)
    {
        if (ModelState.IsValid)
        {
            if (ImagePath != null && ImagePath.Length > 0)
            {
                var filePath = Path.Combine("wwwroot/images", ImagePath.FileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImagePath.CopyToAsync(stream);
                }
                movie.ImagePath = "/images/" + ImagePath.FileName;
            }

            await _movieService.AddMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }
        ViewBag.genres = await _genreService.GetAllGenresAsync();
        return View(movie);
    }
    [HttpGet("{id}")]
    public async Task<IActionResult> Details(int id)
    {
        _logger.LogInformation($"Getting Movie #{id}");
        var movie = await _movieService.GetMovieByIdAsync(id);
        if (movie == null || id == 0)
        {
            return View("NotFound");
        }
        else
        {
            return View(movie);
        }

    }
    [HttpGet]
    public async Task<IActionResult> MoviesAsPDF()
    {
        IEnumerable<Movie> movies = await _movieService.GetAllMoviesAsync();
        return new ViewAsPdf("MoviesAsPdf", movies, ViewData)
        {
            PageMargins = new Rotativa.AspNetCore.Options.Margins(top: 20, left: 20, bottom: 20, right: 20),
            PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape,
        };

    }
}

MoviesReviews.UI/Controllers/ReviewController.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Movie_Review_Website.Models;
using MoviesReviews.Core.Domain.Entities;
using ServiceContracts;

namespace Movie_Review_Website.Controllers
{
    public class ReviewController : Controller
    {
        private readonly ILogger<ReviewController> _logger;
        private readonly IReviewService _reviewService;
        private readonly IMovieService _movieService;
        public ReviewController(ILogger<ReviewController> logger, IReviewService reviewService, IMovieService movieService)
        {
            _reviewService = reviewService;
            _logger = logger;
            _movieService = movieService;
        }
        public async Task< IActionResult> Index()
        {
            _logger.LogInformation($"Getting All Reviews");
            IEnumerable<Review> reviews = await _reviewService.GetAllReviewsAsync();
            return View(reviews);
        }

        [HttpGet]
        public async Task <IActionResult> Add()
        {
            _logger.LogInformation($"Adding a movie");
            ViewBag.movies = await _movieService.GetAllMoviesAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Review review)
        {
            _logger.LogInformation($"Review {review} to be validated");
            if (review.Comment.IsNullOrEmpty() || !ModelState.IsValid)
            {
                _logger.LogWarning($"After validation the review is not valid");
                ViewBag.movies = await _movieService.GetAllMoviesAsync();
                return View(review);
            }
            Movie movie = await _movieService.GetMovieByIdAsync(review.MovieId);
            review.Movie = await _movieService.GetMovieByIdAsync(review.MovieId);
            if(movie == null)
            {
                _logger.LogWarning($"After validation the review is not valid cause the movie id is not found");
                ModelState.AddModelError("","Invalid movie id");
                ViewBag.movies = await _movieService.GetAllMoviesAsync();
                return View(review);
            }
            await _reviewService.AddReviewAsync(review);
            return RedirectToAction("index");
        }

    }
}

MoviesReviews.UI/Views/Shared/NotFound.cshtml
@{
    Layout = "_Layout";
}

<div class="container text-center mt-5">
    <h1 class="display-1 text-danger">404</h1>
    <h2>Oops! Page not found.</h2>
    <p class="lead">The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.</p>
    <a href="/" class="btn btn-primary mt-3"><i class="fas fa-home"></i> Take Me Home</a>
</div>

<style>
    body {
        background-color: #ffffff;
        color: #333333;
    }

    .text-danger {
        color: #e50914 !important;
    }

    .btn-primary {
        background-color: #e50914;
        border-color: #e50914;
    }
</style>

MoviesReviews.UI/Views/Shared/_CustomLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Badri</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Movie_Review_Website.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_NavBarForLoginAndRegisterPartial" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            © 2024 - Badri - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MoviesReviews.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Badri</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Movie_Review_Website.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <header>
        <partial name="_NavBarPartial" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            © @DateTime.Now - Badri - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false) 
</body>
</html>

MoviesReviews.UI/Views/Shared/_NavBarForLoginAndRegisterPartial.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <p class="navbar-brand">Welcome to Badri's Movies</p>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="navbarSupportedContent">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    @if (ViewBag.CurrentUrl == "~/Home/Index")
                    {
                        <a class="nav-link text-dark nav-active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    }
                    else
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    }
                </li>
                <li class="nav-item">
                    @if (ViewBag.CurrentUrl == "~/Home/Privacy")
                    {
                        <a class="nav-link text-dark nav-active" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    }
                    else
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    }
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-action="Login" asp-controller="Account">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Register" asp-controller="Account">Register</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

MoviesReviews.UI/Views/Shared/_NavBarPartial.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <p class="navbar-brand">Welcome to Badri's Movies</p>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" id="navbarSupportedContent">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    @if(ViewBag.CurrentUrl == "~/Home/Index")
                    {
                        <a class="nav-link text-dark nav-active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    }
                    else
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    }
                </li>
                <li class="nav-item">
                    @if (ViewBag.CurrentUrl == "~/Movies/Index")
                    {
                        <a class="nav-link text-dark nav-active" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                    }
                    else
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                    }
                </li>
                <li class="nav-item">
                    @if (ViewBag.CurrentUrl == "~/Genre/Index")
                    {
                        <a class="nav-link text-dark nav-active" asp-area="" asp-controller="Genre" asp-action="Index">Genres</a>
                    }
                    else
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Genres</a>
                    }
                </li>
                <li class="nav-item">
                    @if (ViewBag.CurrentUrl == "~/Review/Index")
                    {
                        <a class="nav-link text-dark nav-active" asp-area="" asp-controller="Review" asp-action="Index">Reviews</a>
                    }
                    else
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="Review" asp-action="Index">Reviews</a>
                    }
                </li>
                <li class="nav-item">
                    @if (ViewBag.CurrentUrl == "~/Home/Privacy")
                    {
                        <a class="nav-link text-dark nav-active" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    }
                    else
                    {
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    }
                </li>
            </ul>
            <ul class="navbar-nav">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <span class="nav-link">@User.Identity?.Name</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Logout" asp-controller="Account">Logout</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Login" asp-controller="Account">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Register" asp-controller="Account">Register</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>